IMR-159 feat : 사용자 인증 기능 추가
boostcampaitech5/level3_recsys_finalproject-recsys-03 pull request #132
Opened 2023-08-10 17:47 UTC by 2jun0

## Overview
- 사용자 인증 기능을 추가합니다.
- jwt를 발행하는 방식으로 하며 access token, refresh token 두개를 발행합니다.
- 우리의 목표는 “사용자 체감 로그인 없이 사용자를 추척하는 것“이므로, 실제로 로그인을 구현하고 로그인 과정이 자동으로 이루어 진다고 보시면 됩니다.

## Change Log
- 모듈: PyJWT 추기
- 서비스: 재로그인, 회원가입, 인증 기능을 하는 AuthService추가
- DB: 사용자 인증정보를 저장하는 AuthDocument, Repository추가
- 예외: UnauthorizedException, BadRequestException추가

## To Reviewer
- 아직 recommendMusic이나 userFeedback과 같은 기능에 사용자 인증을 적용하지 않았습니다.
- 추후 적용 예정입니다.

## Issue Link
- [Jira Issue](https://btcamplevel3.atlassian.net/jira/software/projects/IMR/boards/4?selectedIssue=IMR-159)

2023-08-10 23:32 UTC, kCMI113 requested changes
음~ 인증이란 어렵군요.. 하하 오타만 수정해주시면 죌 것 같아요!

2023-08-10 23:32 UTC, kCMI113 commented on back/src/dto/auth/acesss_payload.py
> +            raise ValidationError("type must equal refresh")
오타인 것 같네용

2023-08-11 04:30 UTC, 2jun0 commented on back/src/dto/auth/acesss_payload.py
> +            raise ValidationError("type must equal refresh")
헐~ 오류도 있어요 두마리 토끼 한번에 잡았네요 감사합니다

2023-08-11 05:30 UTC, kCMI113 commented on back/src/db/document/mixin/date.py
> +    created_at = DateTimeField(default=utcnow)
updated_at 안 쓰고 created_at의 값을 바꾸는 방식인가요?

2023-08-11 05:33 UTC, 2jun0 commented on back/src/db/document/mixin/date.py
> +    created_at = DateTimeField(default=utcnow)
하하 오타입니다 수정할게요!

2023-08-11 12:07 UTC, kCMI113 approved these changes
수고하셨습니당😺👍🏻

2023-08-11 12:07 UTC, merged